# Generated by Django 3.1.4 on 2021-03-27 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppHome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquestions',
            name='hintInfo',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.CreateModel(
            name='HintDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.BooleanField(default=False)),
                ('dtime', models.FloatField()),
                ('question_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppHome.eventquestions')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
