# Generated by Django 3.1.4 on 2021-03-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0003_auto_20210330_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='hintdetail',
            name='attempt',
            field=models.BooleanField(default=False),
        ),
    ]
