# Generated by Django 3.1.4 on 2021-03-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0004_hintdetail_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquestions',
            name='expireTime',
            field=models.IntegerField(default=0),
        ),
    ]
