# Generated by Django 3.1.4 on 2021-03-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0005_eventquestions_expiretime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventquestions',
            old_name='hintInfo',
            new_name='hintInfo1',
        ),
        migrations.AddField(
            model_name='eventquestions',
            name='hintInfo2',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='eventquestions',
            name='hintInfo3',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='eventquestions',
            name='maxScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hintdetail',
            name='qPenalty',
            field=models.IntegerField(default=0),
        ),
    ]
