# Generated by Django 3.1.4 on 2021-03-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0006_auto_20210331_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='hintdetail',
            name='hint1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hintdetail',
            name='hint2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hintdetail',
            name='hint3',
            field=models.BooleanField(default=False),
        ),
    ]
