# Generated by Django 3.1.7 on 2021-04-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0007_auto_20210331_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquestions',
            name='ansFormat',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='eventquestions',
            name='story',
            field=models.CharField(max_length=2000),
        ),
    ]
