# Generated by Django 3.1.7 on 2021-04-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0008_auto_20210401_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='usernm',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='eventquestions',
            name='answer',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='eventquestions',
            name='story',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
